
services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - race-tournament-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
    networks:
      - race-tournament-network

  race-db:
    image: mysql:8.0
    container_name: race-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: race_db
      MYSQL_ROOT_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO : update
      SPRING_JPA_SHOW_SQL : true
    volumes:
      - race-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - race-tournament-network


  race-service:
    build: ./race-service
    container_name: race-service
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
      race-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://race-db:3306/race_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - race-tournament-network

  season-db:
    image: mysql:8.0
    container_name: season-db
    ports:
      - "3010:3306"
    environment:
      MYSQL_DATABASE: season-db
      MYSQL_ROOT_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SQL: true
    volumes:
      - season-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - race-tournament-network


  season-service:
    build: ./season-service
    container_name: season-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      season-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://season-db:3306/season_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - race-tournament-network

  tournament-db:
    image: mysql:8.0
    container_name: tournament-db
    ports:
      - "3011:3306"
    environment:
      MYSQL_DATABASE: tournament-db
      MYSQL_ROOT_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SQL: true
    volumes:
      - tournament-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - race-tournament-network


  tournament-service:
    build: ./tournament-service
    container_name: tournament-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_started
      tournament-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tournament-db:3306/season_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - race-tournament-network


volumes:
  race-db-data:
  season-db-data:
  tournament-db-data:

networks:
  race-tournament-network:
    driver: bridge